const S={
  lw:{minHeight:"100vh",background:"var(--loginBg)",display:"flex",alignItems:"center",justifyContent:"center",fontFamily:"'Segoe UI',Tahoma,sans-serif",direction:"rtl",padding:12},
  lc:{background:"var(--card)",borderRadius:20,padding:"24px 18px",width:"100%",maxWidth:360,textAlign:"center",border:"1px solid var(--border)",boxShadow:"0 20px 40px rgba(0,0,0,0.08)"},
  ug:{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8},
  ub:{background:"#fefefe",border:"2px solid var(--border)",borderRadius:14,padding:"12px 6px",cursor:"pointer",display:"flex",flexDirection:"column",alignItems:"center",gap:2,transition:"all 0.3s",boxShadow:"0 2px 8px rgba(0,0,0,0.04)"},

  app:{minHeight:"100vh",background:"var(--appBg)",fontFamily:"'Segoe UI',Tahoma,sans-serif",color:"var(--text)",paddingBottom:28},
  toast:{position:"fixed",top:10,left:"50%",transform:"translateX(-50%)",background:"var(--card)",color:"var(--text)",padding:"7px 16px",borderRadius:10,fontSize:11,fontWeight:600,zIndex:1000,border:"1px solid var(--border)",boxShadow:"0 6px 16px rgba(0,0,0,0.1)",animation:"toastSlide 0.3s ease"},
  header:{background:"linear-gradient(135deg,#6366f1,#8b5cf6,#ec4899)",padding:"10px 12px 8px",borderRadius:"0 0 16px 16px"},
  hTop:{display:"flex",alignItems:"center",gap:8},
  backBtn:{background:"rgba(255,255,255,0.2)",border:"none",borderRadius:8,width:30,height:30,color:"#fff",fontSize:12,cursor:"pointer",display:"flex",alignItems:"center",justifyContent:"center"},
  bonusFab:{background:"linear-gradient(135deg,#7c3aed,#8b5cf6)",border:"none",borderRadius:8,padding:"5px 10px",color:"#fff",fontSize:10,fontWeight:700,cursor:"pointer"},
  dayRow:{display:"flex",gap:2,marginBottom:10,overflowX:"auto"},
  dayBtn:{flex:1,minWidth:36,padding:"5px 2px",background:"var(--inputBg)",border:"2px solid transparent",borderRadius:8,cursor:"pointer",display:"flex",flexDirection:"column",alignItems:"center",gap:0,transition:"all 0.2s",color:"var(--textTer)"},
  dayAct:{background:"rgba(99,102,241,0.15)",borderColor:"#6366f1",color:"#4338ca"},
  tabs:{display:"flex",gap:1,padding:"6px 8px 0",justifyContent:"center"},
  tab:{padding:"7px 12px",background:"transparent",border:"none",borderBottom:"2px solid transparent",color:"var(--textSec)",fontSize:14,cursor:"pointer",borderRadius:"6px 6px 0 0",transition:"all 0.2s"},
  tabA:{color:"#6366f1",borderBottomColor:"#6366f1",background:"rgba(99,102,241,0.08)"},
  subT:{padding:"5px 10px",background:"var(--barBg)",border:"1px solid var(--border)",borderRadius:8,color:"var(--textTer)",fontSize:11,fontWeight:600,cursor:"pointer",whiteSpace:"nowrap"},
  content:{padding:"10px 10px 20px"},
  secH:{display:"flex",alignItems:"center",gap:6,marginBottom:5,padding:"0 2px"},
  bdg:{marginRight:"auto",marginLeft:0,fontSize:9,color:"var(--textTer)",fontWeight:600,background:"var(--barBg)",padding:"1px 7px",borderRadius:7},
  st:{fontSize:15,fontWeight:800,color:"var(--text)",margin:"0 0 10px"},

  tc:{background:"var(--card)",borderRadius:10,padding:"8px 10px",marginBottom:3,border:"1px solid var(--border)",transition:"all 0.3s",boxShadow:"0 1px 3px rgba(0,0,0,0.04)"},
  tD:{borderColor:"#f59e0b40",background:"linear-gradient(135deg,#fffbeb,#fef3c7)"},
  tA:{borderColor:"#10b98140",background:"linear-gradient(135deg,#ecfdf5,#d1fae5)"},
  tr:{display:"flex",alignItems:"center",gap:7},
  wt:{fontSize:8,fontWeight:700,color:"#6366f1",background:"#6366f115",padding:"1px 5px",borderRadius:5},

  wB:{width:26,height:26,background:"var(--barBg)",border:"1px solid var(--border)",borderRadius:6,color:"var(--text)",fontSize:14,fontWeight:700,cursor:"pointer",display:"flex",alignItems:"center",justifyContent:"center"},
  wBs:{width:18,height:18,background:"var(--barBg)",border:"1px solid var(--border)",borderRadius:4,color:"var(--text)",fontSize:12,fontWeight:700,cursor:"pointer",display:"flex",alignItems:"center",justifyContent:"center"},

  doneBtn:{minWidth:34,height:34,background:"#10b981",border:"none",borderRadius:9,color:"#fff",fontSize:15,fontWeight:700,cursor:"pointer",display:"flex",alignItems:"center",justifyContent:"center"},
  camBtn:{minWidth:34,height:34,background:"#6366f1",border:"none",borderRadius:9,color:"#fff",fontSize:13,cursor:"pointer",display:"flex",alignItems:"center",justifyContent:"center"},
  okBtn:{minWidth:28,height:28,background:"#10b981",border:"none",borderRadius:7,color:"#fff",fontSize:13,cursor:"pointer",display:"flex",alignItems:"center",justifyContent:"center"},
  noBtn:{minWidth:28,height:28,background:"#ef4444",border:"none",borderRadius:7,color:"#fff",fontSize:11,cursor:"pointer",display:"flex",alignItems:"center",justifyContent:"center"},
  vBtn:{padding:"3px 5px",background:"rgba(99,102,241,0.1)",border:"1px solid #6366f130",borderRadius:5,color:"#6366f1",fontSize:10,cursor:"pointer"},
  eBtn:{padding:"3px 8px",background:"#6366f110",border:"1px solid #6366f130",borderRadius:6,color:"#6366f1",fontSize:10,cursor:"pointer"},
  dBtn:{padding:"3px 6px",background:"#ef444410",border:"1px solid #ef444430",borderRadius:6,color:"#ef4444",fontSize:10,cursor:"pointer"},
  bOk:{flex:1,padding:8,background:"#10b981",border:"none",borderRadius:8,color:"#fff",fontSize:12,fontWeight:700,cursor:"pointer"},
  bNo:{flex:1,padding:8,background:"#ef4444",border:"none",borderRadius:8,color:"#fff",fontSize:12,fontWeight:700,cursor:"pointer"},

  dc:{background:"var(--card)",borderRadius:12,padding:12,marginBottom:8,border:"1px solid var(--border)",boxShadow:"0 1px 3px rgba(0,0,0,0.04)"},

  inp:{width:"100%",padding:"8px 10px",background:"var(--inputBg)",border:"1px solid var(--border)",borderRadius:8,color:"var(--text)",fontSize:12,outline:"none",marginBottom:8,boxSizing:"border-box",direction:"rtl"},
  chip:{padding:"4px 8px",background:"var(--inputBg)",border:"2px solid var(--border)",borderRadius:14,cursor:"pointer",fontSize:10,color:"var(--textTer)",fontWeight:600,transition:"all 0.2s"},

  ov:{position:"fixed",inset:0,background:"var(--overlay)",backdropFilter:"blur(4px)",display:"flex",alignItems:"center",justifyContent:"center",zIndex:999,padding:12},
  md:{background:"var(--card)",borderRadius:16,padding:18,width:"100%",maxWidth:300,border:"1px solid var(--border)",direction:"rtl",maxHeight:"88vh",overflowY:"auto",boxShadow:"0 20px 40px rgba(0,0,0,0.12)",animation:"cardPop 0.2s ease"},
  mt:{fontSize:14,fontWeight:800,color:"var(--text)",margin:"0 0 8px",textAlign:"center"},
  mc:{width:"100%",padding:6,background:"transparent",border:"none",color:"var(--textSec)",fontSize:10,cursor:"pointer"},
  rpGrid:{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginBottom:14},
  rpCard:{background:"var(--card)",borderRadius:12,padding:14,textAlign:"center",border:"1px solid var(--border)",boxShadow:"0 1px 3px rgba(0,0,0,0.04)"},
  rpBig:{fontSize:24,fontWeight:800,color:"var(--text)",marginBottom:0},
  rpLabel:{fontSize:9,color:"var(--textTer)",fontWeight:600,marginTop:4},
  rpSection:{background:"var(--card)",borderRadius:14,padding:14,marginBottom:12,border:"1px solid var(--border)"},
  rpSt:{fontSize:13,fontWeight:800,color:"var(--text)",marginBottom:10,textAlign:"center"},
  rpBar:{height:18,borderRadius:6,transition:"width 0.5s ease"},
  rpBarBg:{height:18,background:"var(--barBg)",borderRadius:6,overflow:"hidden",marginBottom:4},
  rpHeatCell:{width:"100%",aspectRatio:"1",borderRadius:2,minWidth:0},
  rpHeatGrid:{display:"grid",gridTemplateColumns:"28px repeat(24,1fr)",gap:1,fontSize:7},
  rpAchieve:{display:"flex",alignItems:"center",gap:8,padding:"8px 0",borderBottom:"1px solid #f1f5f9"},
};
export default S;
